replicaCount: 4

image:
  pullPolicy: Always

service:
  type: NodePort
  port: 8080

springdemoimage: 0.77.0
databaseurl: "jdbc:mysql://192.168.1.151:3306/demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"


