kind: ConfigMap 
apiVersion: v1 
metadata:
  name: spring-demo-configmap 
data:
  # Configuration values can be set as key-value properties
  database_uri: {{.Values.databaseurl | quote}}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name}}-spring-demo
  labels:
    version: {{.Chart.Version}}
    app: spring-demo
    release: {{.Release.Name}}
spec:
  containers:
  - image: "harbor.ellin.net/library/spring-demo:{{ .Values.springdemoimage }}"
    imagePullPolicy: Always
    name: spring-demo
    env:
    - name: SPRING_DATASOURCE_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysql-creds
          key: username
    - name: SPRING_DATASOURCE_PASSWORD
      valueFrom:
        configMapRef:
          name: mysql-creds
          key: password
    - name: SPRING_DATASOURCE_URL
  valueFrom:
    secretKeyRef:
      name: pring-demo-configmap
      key: database_uri
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-spring-demo-service
  labels:
    app: spring-demo
    version: {{.Chart.Version}}
    release: {{.Release.Name}}
    
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: spring-demo  
    version: {{.Chart.Version}}
    release: {{.Release.Name}}
