---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.ellin.net:443/library/kubernetes-resource
    insecure_registries:
      - harbor.ellin.net:443
    tag: latest

params:
  - PKS_ENDPOINT: ((PKS_ENDPOINT))
  - PKS_USER: ((PKS_USER))
  - PKS_PASSWORD: ((PKS_PASSWORD))
  - PKS_CLUSTER: ((PKS_CLUSTER))
  - DB_USER: ((dbusername))
  - DB_PASSWORD: ((dbpassword))

inputs:
  - name: helm-chart
  - name: config
run:
  path: /bin/bash
  args:
    - helm-chart/ci/tasks/push-pks.sh